/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as PathRouteImport } from './routes/path'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/drill': typeof DrillRoute
  '/path': typeof PathRoute
  '/projects': typeof ProjectsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/drill': typeof DrillRoute
  '/path': typeof PathRoute
  '/projects': typeof ProjectsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/drill': typeof DrillRoute
  '/path': typeof PathRoute
  '/projects': typeof ProjectsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/drill'
    | '/path'
    | '/projects'
    | '/learn/$slug'
    | '/quiz/$slug'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/drill'
    | '/path'
    | '/projects'
    | '/learn/$slug'
    | '/quiz/$slug'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/drill'
    | '/path'
    | '/projects'
    | '/learn/$slug'
    | '/quiz/$slug'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  DrillRoute: typeof DrillRoute
  PathRoute: typeof PathRoute
  ProjectsRoute: typeof ProjectsRoute
  LearnSlugRoute: typeof LearnSlugRoute
  QuizSlugRoute: typeof QuizSlugRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  DrillRoute: DrillRoute,
  PathRoute: PathRoute,
  ProjectsRoute: ProjectsRoute,
  LearnSlugRoute: LearnSlugRoute,
  QuizSlugRoute: QuizSlugRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
